version: "3.1"

services:
  postgres-db:
    container_name: notes-app
    image: postgres:14
    env_file: 
      - .env
    environment:
      POSTGRES_PASSWORD: ${PGPASSWORD}
      POSTGRES_USER: ${PGUSER}
      POSTGRES_DB: ${PGDATABASE}

    ports:
      - ${PGPORT}:5432
    volumes:
      - ./database:/var/lib/postgresql